defaults: &defaults
  working_directory: /tmp/storybook
  docker:
    - image: node:8

version: 2
dependencies:
  pre:
    - npm install -g npm
jobs:
  validate:
    <<: *defaults
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-dependencies-{{ checksum "package.json" }}
            - root-dependencies-
      - run:
          name: "Install root dependencies"
          command: |
            yarn install
      - save_cache:
          key: root-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - restore_cache:
          keys:
            - package-dependencies-{{ checksum "package.json" }}
            - package-dependencies-
      - run:
          name: "Bootstrapping"
          command: |
            npm run bootstrap -- --concurrency 1 --npm-client=yarn
      - save_cache:
          key: package-dependencies-{{ checksum "package.json" }}
          paths:
            - app/**/node_modules
            - docs/**/node_modules
            - examples/**/node_modules
            - lib/**/node_modules
  example-kitchen-sink:
    <<: *defaults
    steps:
      - run:
          name: "Running kitchen-sink"
          command: |
            echo "TODO"
  example-test-cra:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-dependencies-{{ checksum "package.json" }}
            - root-dependencies-
      - run:
          name: "Install root dependencies"
          command: |
            yarn install
      - run:
          name: "Bootstrapping"
          command: |
            npm run bootstrap -- --concurrency 1 --npm-client=yarn
            npm run bootstrap:test-cra
      - run:
          name: "Running test-cra"
          command: |
            echo "TODO"
  example-react-native:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-dependencies-{{ checksum "package.json" }}
            - root-dependencies-
      - run:
          name: "Install root dependencies"
          command: |
            yarn install
      - run:
          name: "Bootstrapping packages"
          command: |
            npm run bootstrap -- --concurrency 1 --npm-client=yarn
            npm run bootstrap:react-native-vanilla
      - run:
          name: "Running react-native"
          command: |
            echo "TODO"

  docs:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-dependencies-{{ checksum "package.json" }}
            - root-dependencies-
      - run:
          name: "Install root dependencies"
          command: |
            yarn install
      - run:
          name: "Bootstrapping"
          command: |
            npm run bootstrap:docs
      - run:
          name: "Running docs"
          command: |
            npm run docs:build
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-dependencies-{{ checksum "package.json" }}
            - root-dependencies-
      - run:
          name: "Install root dependencies"
          command: |
            yarn install
      - run:
          name: "Linting"
          command: |
            npm run lint
  unit-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-dependencies-{{ checksum "package.json" }}
            - root-dependencies-
      - run:
          name: "Install root dependencies"
          command: |
            yarn install
      - run:
          name: "Bootstrapping"
          command: |
            npm run bootstrap:docs
            npm run bootstrap:test-cra
            npm run bootstrap:react-native-vanilla
            npm run bootstrap -- --concurrency 1 --npm-client=yarn
      - run:
          name: "Unit testing"
          command: |
            npm run test -- --coverage
            npm run coverage        

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - validate
      - build
      - example-kitchen-sink
      - example-test-cra
      - example-react-native
      - docs
      - lint
      - unit-test
      - deploy:
          requires:
            - lint
            - unit-test
            - docs
